apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-scsi-1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Block
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local
  local:
    path: /dev/dm-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-scsi-1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm
  name: vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm
    spec:
      nodeSelector:
        kubernetes.io/hostname: node02
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: root
          - disk:
              bus: virtio
            name: cloudinitdisk
          - lun:
              bus: scsi
              reservation: true
            name: scsidisk
          interfaces:
          - masquerade: {}
            name: default
        resources:
          requests:
            memory: 1Gi
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/fedora-with-test-tooling-container-disk:devel
        name: root
      - name: scsidisk
        persistentVolumeClaim:
          claimName: pvc-scsi-1
      - cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
      networks:
      - name: default
        pod: {}
